# Site settings
title: Coconut
SEOTitle: 信的博客 | Coconut
header-img: https://unsplash.it/1900/870?random
favicon: https://unsplash.it/16/16?random
page-img: https://unsplash.it/1900/870?random
avatar: https://unsplash.it/400/400?random
email: xinabner@gmail.com
description: ""
keyword: ""
url: ""              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'


# SNS settings
RSS: false
weibo_username: CoconutCool
zhihu_username: CoconutCool
github_username: CoconutCool
#twitter_username:
# facebook_username:



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: CoconutCool
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "魔都上海的一个还未入门的程序员， 今年才毕业， 励志造造轮子什么的， Coconut， 闲来写字的地方。"
sidebar-avatar: https://unsplash.it/400/400?random     # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value